Algoritmo "exe7_nomecompleto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Octávio Nogueira
// Data atual  : 25/03/2022
Var
// Seção de Declarações das variáveis
   nome, snome, ncompleto: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite seu nome ")
   leia(nome)

   escreva("Digite seu sobrenome ")
   leia(snome)

   ncompleto <- nome + " " + snome

   escreva(ncompleto)

Fimalgoritmo