Algoritmo "EXERCÍCIO 01 DA APOSTIA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Octávio Nogueira
// Data atual  : 03/04/2022
var:
 x, y: inteiro
 inicio
         escreval("Digite o primeiro número: ")
      leia(x)
           escreval("Digite o segundo número: ")
      leia(y)
             escreva("A soma dos números é: ",x+y)
fimalgoritmo
