Algoritmo "EXERCÍCIO 02 DA APOSTIA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Octávio Nogueira
// Data atual  : 03/04/2022

var
 x, y: real
inicio

escreva("Digite o primeiro número: ")
leia(x)
escreva("Digite o segundo número: ")
leia(y)

escreval("A soma é: ",x+y)
escreval("A subtração é: ",x-y)
escreval("A multiplicação é: ",x*y)
escreval("A divisão é: ",x/y)


fimalgoritmo
